config:
  credentials: []
  project_repos:
    code-repo.d4science.org/MaDgIK/openaire-library:
      branch: master
      repo: https://code-repo.d4science.org/MaDgIK/openaire-library.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/MaDgIK/openaire-library git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-grey-otter.sh
        container: qc.acc_lumpy-sangria-guppy
  QC.Doc:
    repos:
      code-repo.d4science.org/MaDgIK/openaire-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-salmon-baboon.sh
        container: qc.doc_surly-amethyst-cockroach
      code-repo.d4science.org/MaDgIK/openaire-library git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-orchid-oyster.sh
        container: qc.doc_messy-gold-seal
  QC.Lic:
    repos:
      code-repo.d4science.org/MaDgIK/openaire-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-lime-kingfisher.sh
        container: qc.lic_craggy-puce-leopard
  QC.Ver:
    repos:
      code-repo.d4science.org/MaDgIK/openaire-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-myrtle-horse.sh
        container: qc.ver_woolly-carmine-bear
timeout: 5400
